### ISSUE TITLE
Support opening a file with a command-line argument

### ISSUE THREAD

**Issue by akien-mga** [MBach/Miam-Player#10]
Currently it is not possible to open a music file (or playlist, for that matter) with ```miam-player $filename``` when Miam-Player is installed on the system.

It would be a prerequisite in order to be able to load music files directly with a double click (if miam-player is the default music player) or with something like right click > open with > Miam-Player (provided the system's desktop file provides the correct MIME type associations).

**Comment by MBach** [comment]
Actually, a draft was made a long time ago in order to support Right-click > open with Miam-Player.

    if (command == "-f") { // Append to playlist
        convertArgs();
        tabPlaylists->insertItemsToPlaylist(-1, tracks);
    } else if (command == "-n") { // New playlist
        convertArgs();
        Playlist *p = tabPlaylists->addPlaylist();
        if (p) {
            tabPlaylists->insertItemsToPlaylist(-1, tracks);
        }
    } else if (command == "-t") { // Tag Editor
        convertArgs();
        tagEditor->addItemsToEditor(tracks);
        showTagEditor();
    } else if (command == "-l") { // Library
    
    }

It was tested on Windows when I wrote a Shell Extension for Windows Explorer. It probably needs some adjustments to work nicely on Linux.

**Comment by MBach** [comment]
Now you can do:
```
Usage: ./miam-player [options] [files]
Command line helper for Miam-Player
 
Options:
  -h, --help             Displays this help.
  -d, --directory <dir>  Directory to open.
  -n, --new-playlist     Medias are added into a new playlist.
  -t, --tag-editor       Medias are sent to tag editor.
  -l, --library          Directory is sent to library.
  -p, --play             Play or pause track in active playlist.
  -s, --stop             Stop playback.
  -f, --forward          Play next track.
  -b, --backward         Play previous track.
  -v, --volume <volume>  Set volume of the player.
 
Arguments:
  files                  Files to open
```

Example: 
```./miam-player -t ~/Music/Bonobo/2001_-_Animal_Magic/01_-_Intro.mp3```
will send above track directly in the Tag Editor

**Comment by akien-mga** [comment]
Wow nice :)
I'll try this asap.
