### ISSUE TITLE
tableview.cpp:26:31: error: no matching function for call to 'QAction::QAction()'

### ISSUE THREAD

**Issue by martinkg** [MBach/Miam-Player#103]
compilation fails on Fedora 24 with recent git release:

`make[1]: Leaving directory '/home/martin/rpmbuild/BUILD/Miam-Player-2be69a1696823103f7d36b141faef8cdd05557af/src/TabPlaylists'
cd src/UniqueLibrary/ && ( test -e Makefile || /usr/lib64/qt5/bin/qmake /home/martin/rpmbuild/BUILD/Miam-Player-2be69a1696823103f7d36b141faef8cdd05557af/src/UniqueLibrary/UniqueLibrary.pro 'QMAKE_CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' 'QMAKE_CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' QMAKE_LFLAGS=-Wl,--as-needed LIB_SUFFIX=64 'CONFIG+=no_rpath recheck config_libass_link debug' -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/martin/rpmbuild/BUILD/Miam-Player-2be69a1696823103f7d36b141faef8cdd05557af/src/UniqueLibrary'
/usr/lib64/qt5/bin/uic uniquelibrary.ui -o ui_uniquelibrary.h
g++ -c -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -g -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DMIAMUNIQUELIBRARY_LIBRARY -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../Core -I../Library -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -Idebug/.moc -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o debug/.obj/coveritem.o coveritem.cpp
g++ -c -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -g -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DMIAMUNIQUELIBRARY_LIBRARY -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../Core -I../Library -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -Idebug/.moc -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o debug/.obj/tableview.o tableview.cpp
g++ -c -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -g -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DMIAMUNIQUELIBRARY_LIBRARY -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../Core -I../Library -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -Idebug/.moc -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o debug/.obj/uniquelibraryitemdelegate.o uniquelibraryitemdelegate.cpp
g++ -c -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -g -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DMIAMUNIQUELIBRARY_LIBRARY -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../Core -I../Library -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -Idebug/.moc -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o debug/.obj/uniquelibraryitemmodel.o uniquelibraryitemmodel.cpp
tableview.cpp: In constructor 'TableView::TableView(QWidget*)':
tableview.cpp:26:31: error: no matching function for call to 'QAction::QAction()'
  , _actionSendToTagEditor(new QAction)
                               ^~~~~~~
In file included from /usr/include/qt5/QtWidgets/qmenu.h:40:0,
                 from /usr/include/qt5/QtWidgets/QMenu:1,
                 from tableview.h:4,
                 from tableview.cpp:1:
/usr/include/qt5/QtWidgets/qaction.h:174:5: note: candidate: QAction::QAction(QActionPrivate&, QObject*)
     QAction(QActionPrivate &dd, QObject *parent);
     ^~~~~~~
/usr/include/qt5/QtWidgets/qaction.h:174:5: note:   candidate expects 2 arguments, 0 provided
/usr/include/qt5/QtWidgets/qaction.h:89:5: note: candidate: QAction::QAction(const QIcon&, const QString&, QObject*)
     QAction(const QIcon &icon, const QString &text, QObject* parent);
     ^~~~~~~
/usr/include/qt5/QtWidgets/qaction.h:89:5: note:   candidate expects 3 arguments, 0 provided
/usr/include/qt5/QtWidgets/qaction.h:88:5: note: candidate: QAction::QAction(const QString&, QObject*)
     QAction(const QString &text, QObject* parent);
     ^~~~~~~
/usr/include/qt5/QtWidgets/qaction.h:88:5: note:   candidate expects 2 arguments, 0 provided
/usr/include/qt5/QtWidgets/qaction.h:87:14: note: candidate: QAction::QAction(QObject*)
     explicit QAction(QObject* parent);
              ^~~~~~~
/usr/include/qt5/QtWidgets/qaction.h:87:14: note:   candidate expects 1 argument, 0 provided
Makefile:678: recipe for target 'debug/.obj/tableview.o' failed
make[1]: *** [debug/.obj/tableview.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/martin/rpmbuild/BUILD/Miam-Player-2be69a1696823103f7d36b141faef8cdd05557af/src/UniqueLibrary'
Makefile:175: recipe for target 'sub-src-UniqueLibrary-make_first-ordered' failed
make: *** [sub-src-UniqueLibrary-make_first-ordered] Error 2`

used qt5 and qtav-devel version:
qt5-qtbase-devel-5.6.0
qtav-devel-1.11.0-0.1git3b418cb

**Comment by MBach** [comment]
Should pass with commit https://github.com/MBach/Miam-Player/commit/ba183b055054a9baf611f856b4a287fd4b18e521

**Comment by martinkg** [comment]
works for me, thanks.
