### ISSUE TITLE
remotecontrol.cpp:43:16: error: 'Qt_5_7' is not a member of 'QDataStream'

### ISSUE THREAD

**Issue by martinkg** [MBach/Miam-Player#104]
Hi,
i tried to compile the recent git version on Fedora, but this fails with the following error messages:

`/usr/lib64/qt5/bin/moc -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB --include debug/.moc/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/martin/rpmbuild/BUILD/Miam-Player-c9c4ebaac856312ed7775de6356d4f0aba2e07ac/src/Player -I/home/martin/rpmbuild/BUILD/Miam-Player-c9c4ebaac856312ed7775de6356d4f0aba2e07ac/src/Core/3rdparty -I/home/martin/rpmbuild/BUILD/Miam-Player-c9c4ebaac856312ed7775de6356d4f0aba2e07ac/src/Player/dialogs -I/home/martin/rpmbuild/BUILD/Miam-Player-c9c4ebaac856312ed7775de6356d4f0aba2e07ac/src/Player/filesystem -I/home/martin/rpmbuild/BUILD/Miam-Player-c9c4ebaac856312ed7775de6356d4f0aba2e07ac/src/Player/playlists -I/home/martin/rpmbuild/BUILD/Miam-Player-c9c4ebaac856312ed7775de6356d4f0aba2e07ac/src/Player/views -I/home/martin/rpmbuild/BUILD/Miam-Player-c9c4ebaac856312ed7775de6356d4f0aba2e07ac/src/Player/views/tageditor -I/home/martin/rpmbuild/BUILD/Miam-Player-c9c4ebaac856312ed7775de6356d4f0aba2e07ac/src/Core -I/home/martin/rpmbuild/BUILD/Miam-Player-c9c4ebaac856312ed7775de6356d4f0aba2e07ac/src/Library -I/home/martin/rpmbuild/BUILD/Miam-Player-c9c4ebaac856312ed7775de6356d4f0aba2e07ac/src/TabPlaylists -I/home/martin/rpmbuild/BUILD/Miam-Player-c9c4ebaac856312ed7775de6356d4f0aba2e07ac/src/UniqueLibrary -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-redhat-linux -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.1.1/include -I/usr/local/include -I/usr/include dialogs/customizethemedialog.h -o debug/.moc/moc_customizethemedialog.cpp
remotecontrol.cpp: In member function 'void RemoteControl::decodeResponseFromClient()':
remotecontrol.cpp:43:16: error: 'Qt_5_7' is not a member of 'QDataStream'
  in.setVersion(QDataStream::Qt_5_7);
                ^~~~~~~~~~~
remotecontrol.cpp:44:5: error: 'class QDataStream' has no member named 'startTransaction'
  in.startTransaction();
     ^~~~~~~~~~~~~~~~
remotecontrol.cpp:51:10: error: 'class QDataStream' has no member named 'commitTransaction'
  if (!in.commitTransaction()) {
          ^~~~~~~~~~~~~~~~~
remotecontrol.cpp: In member function 'void RemoteControl::initializeConnection()':
remotecontrol.cpp:85:17: error: 'Qt_5_7' is not a member of 'QDataStream'
  out.setVersion(QDataStream::Qt_5_7);
                 ^~~~~~~~~~~
remotecontrol.cpp: In member function 'void RemoteControl::mediaPlayerStatedChanged(QMediaPlayer::State)':
remotecontrol.cpp:116:17: error: 'Qt_5_7' is not a member of 'QDataStream'
  out.setVersion(QDataStream::Qt_5_7);
                 ^~~~~~~~~~~
remotecontrol.cpp: In member function 'void RemoteControl::sendPlaylists() const':
remotecontrol.cpp:135:17: error: 'Qt_5_7' is not a member of 'QDataStream'
  out.setVersion(QDataStream::Qt_5_7);
                 ^~~~~~~~~~~
remotecontrol.cpp: In member function 'void RemoteControl::sendTrackInfos(const QString&)':
remotecontrol.cpp:159:17: error: 'Qt_5_7' is not a member of 'QDataStream'
  out.setVersion(QDataStream::Qt_5_7);
                 ^~~~~~~~~~~
Makefile:1552: recipe for target 'debug/.obj/remotecontrol.o' failed
make[1]: *** [debug/.obj/remotecontrol.o] Error 1
make[1]: *** Waiting for unfinished jobs....`

thanks

**Comment by MBach** [comment]
I suppose you have Qt < 5.7.0 on your computer. Actually, this isn't very important to have the latest Qt release in order to use QDataStream. I can lower to Qt 5.6 for instance.

**Comment by martinkg** [comment]
yes i have qt5-qtbase-5.6.1-3.fc24.x86_64 installed.
if you can lower the version that would be great.
