### ISSUE TITLE
build fails with 0.8.1 git on fedora

### ISSUE THREAD

**Issue by martinkg** [MBach/Miam-Player#105]
make[1]: Leaving directory '/home/martin/rpmbuild/BUILD/Miam-Player-193ab01107604141e84c7dd325b387ead41a225e/src/UniqueLibrary'
cd src/Player/ && ( test -e Makefile || /usr/lib64/qt5/bin/qmake /home/martin/rpmbuild/BUILD/Miam-Player-193ab01107604141e84c7dd325b387ead41a225e/src/Player/Player.pro 'QMAKE_CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' 'QMAKE_CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' QMAKE_LFLAGS=-Wl,--as-needed LIB_SUFFIX=64 'CONFIG+=no_rpath recheck config_libass_link debug' -o Makefile ) && make -f Makefile 
Project ERROR: Unknown module(s) in QT: websockets
Makefile:218: recipe for target 'sub-src-Player-make_first-ordered' failed
make: *** [sub-src-Player-make_first-ordered] Error 3

**Comment by MBach** [comment]
Hi,
That's strange, QWebSocket class was introduced in Qt 5.3, which was released in 2014: [see blog](http://blog.qt.io/blog/2014/05/20/qt-5-3-released/)!

> QWebSocket Class
> Implements a TCP socket that talks the WebSocket protocol. More...
> 
> Header:
> #include <QWebSocket> 
> qmake:
> QT += websockets
> Since:
> Qt 5.3
> Inherits:
> QObject

**Comment by martinkg** [comment]
on fedora the dev package qt5-qtwebsockets-devel must be installed.
Thanks for your feedback.

**Comment by MBach** [comment]
No problemo
