### ISSUE TITLE
Importing playlists

### ISSUE THREAD

**Issue by gargargarrick** [MBach/Miam-Player#108]
I recently discovered Miam (it's lovely so far!), and have a few dozen .xspf and .m3u playlists already that I'd like to use in it. Some of these are relatively large -- one has over 400 items -- and would be difficult or tedious to recreate manually. Is there any functionality to import an existing playlist file into the Playlist Manager, or any plans to add such a thing if not? Thanks in any case.

**Comment by MBach** [comment]
Hi,
Actually, I have just made an export to m3u, but I cannot import external playlists. It shouldn't be too difficult to realize. For XSPF file format, it can be a little more tricky, because inside, files can be in Windows / Linux format, and relative or absolute.

**Comment by MBach** [comment]
Done, and will be included in next release.
