### ISSUE TITLE
undefined reference to `chromaprint_get_raw_fingerprint'

### ISSUE THREAD

**Issue by martinkg** [MBach/Miam-Player#109]
when compiling the recent git version https://github.com/MBach/Miam-Player/commit/84d6911c687c55675099ada3e3d09571b0eb4a2f  on Fedora 25 i get the following error:

 `g++ -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--as-needed -o miam-player debug/.obj/qtlocalpeer.o debug/.obj/qtsingleapplication.o debug/.obj/qtsinglecoreapplication.o debug/.obj/logbrowser.o debug/.obj/logbrowserdialog.o debug/.obj/colordialog.o debug/.obj/customizeoptionsdialog.o debug/.obj/customizethemedialog.o debug/.obj/customizethemetaglineedit.o debug/.obj/dragdropdialog.o debug/.obj/equalizerdalog.o debug/.obj/reflector.o debug/.obj/starswidget.o debug/.obj/miamstyle.o debug/.obj/viewloader.o debug/.obj/columnutils.o debug/.obj/main.o debug/.obj/mainwindow.o debug/.obj/pluginmanager.o debug/.obj/quickstart.o debug/.obj/tracksnotfoundmessagebox.o debug/.obj/remotecontrol.o debug/.obj/minimodewidget.o debug/.obj/minislider.o debug/.obj/qrc_player.o debug/.obj/moc_qtlocalpeer.o debug/.obj/moc_qtsingleapplication.o debug/.obj/moc_qtsinglecoreapplication.o debug/.obj/moc_logbrowser.o debug/.obj/moc_logbrowserdialog.o debug/.obj/moc_colordialog.o debug/.obj/moc_customizeoptionsdialog.o debug/.obj/moc_customizethemedialog.o debug/.obj/moc_customizethemetaglineedit.o debug/.obj/moc_dragdropdialog.o debug/.obj/moc_equalizerdalog.o debug/.obj/moc_reflector.o debug/.obj/moc_starswidget.o debug/.obj/moc_miamstyle.o debug/.obj/moc_mainwindow.o debug/.obj/moc_pluginmanager.o debug/.obj/moc_quickstart.o debug/.obj/moc_tracksnotfoundmessagebox.o debug/.obj/moc_remotecontrol.o debug/.obj/moc_minimodewidget.o debug/.obj/moc_minislider.o   -L/home/martin/rpmbuild/BUILD/Miam-Player-84d6911c687c55675099ada3e3d09571b0eb4a2f/src/player/../core/ -lmiam-core -L/home/martin/rpmbuild/BUILD/Miam-Player-84d6911c687c55675099ada3e3d09571b0eb4a2f/src/player/../library/ -lmiam-library -L/home/martin/rpmbuild/BUILD/Miam-Player-84d6911c687c55675099ada3e3d09571b0eb4a2f/src/player/../tabplaylists/ -lmiam-tabplaylists -L/home/martin/rpmbuild/BUILD/Miam-Player-84d6911c687c55675099ada3e3d09571b0eb4a2f/src/player/../uniquelibrary/ -lmiam-uniquelibrary -L/home/martin/rpmbuild/BUILD/Miam-Player-84d6911c687c55675099ada3e3d09571b0eb4a2f/src/player/../cover-fetcher/ -lmiam-coverfetcher -L/home/martin/rpmbuild/BUILD/Miam-Player-84d6911c687c55675099ada3e3d09571b0eb4a2f/src/player/../acoustid/ -lmiam-acoustid -L/home/martin/rpmbuild/BUILD/Miam-Player-84d6911c687c55675099ada3e3d09571b0eb4a2f/src/player/../tageditor/ -lmiam-tageditor -lQt5Widgets -lQt5Multimedia -lQt5Gui -lQt5WebSockets -lQt5Network -lQt5Sql -lQt5Core -lGL -lpthread 
/home/martin/rpmbuild/BUILD/Miam-Player-84d6911c687c55675099ada3e3d09571b0eb4a2f/src/player/../acoustid//libmiam-acoustid.so: undefined reference to `chromaprint_get_raw_fingerprint'
/home/martin/rpmbuild/BUILD/Miam-Player-84d6911c687c55675099ada3e3d09571b0eb4a2f/src/player/../acoustid//libmiam-acoustid.so: undefined reference to `chromaprint_dealloc'
/home/martin/rpmbuild/BUILD/Miam-Player-84d6911c687c55675099ada3e3d09571b0eb4a2f/src/player/../acoustid//libmiam-acoustid.so: undefined reference to `chromaprint_get_fingerprint'
/home/martin/rpmbuild/BUILD/Miam-Player-84d6911c687c55675099ada3e3d09571b0eb4a2f/src/player/../acoustid//libmiam-acoustid.so: undefined reference to `chromaprint_new'`

**Comment by MBach** [comment]
I'm using a new library (chromaprint / acoustid) in order to do fingerprinting and fetching results from the webservice.

The following dependency is required:

    dnf install libchromaprint-devel.x86_64 libchromaprint.x86_64

I have changed the .pro file accordingly:

    LIBS += -L$$OUT_PWD/../core/ -lmiam-core -ltag -lchromaprint

However, I've still have a crash at startup ...

**Comment by martinkg** [comment]
works now.
Thanks.
