### ISSUE TITLE
libmiam-acoustid.so.1 is missing when running miam-player

### ISSUE THREAD

**Issue by martinkg** [MBach/Miam-Player#110]
I compiled the recent miam-player successfully on Fedora 25, but running the application fails with:
$ miam-player 
miam-player: error while loading shared libraries: libmiam-acoustid.so.1: cannot open shared object file: No such file or directory

**Comment by MBach** [comment]
Hi,
Could you please explain how do you compile and launch the program? I'm having difficulties to launch it throught Qt Creator on Fedora 25.

**Comment by martinkg** [comment]
$ cd ~/rpmbuild/SPECS
$ wget https://martinkg.fedorapeople.org/Packages/miam-player/miam-player.spec
$ spectool -g miam-player.spec
$ mv miam-player-a057928.tar.gz ../SOURCES/
$ rpmbuild -ba miam-player.spec
# rpm -ivh --nodeps ~/rpmbuild/RPMS/x86_64/miam-player-0.8.1-0.8gita057928.fc25.x86_64.rpm
$ miam-player

**Comment by MBach** [comment]
I've tried to build it by myself and for `rpmbuild -ba miam-player.spec` I have this error:

    Error on file "/home/mbach/rpmbuild/SOURCES/miam-player.desktop": No such file or directory
    error : Bad output status for /var/tmp/rpm-tmp.jcXSsL (%install)

([here you can find the temporary file](http://pastebin.com/CLmNY6HV))

One more thing, about the patch `remotecontrol.patch`, is this still valid? I'm including the following class a few lines later:

    #include <QDataStream>

**Comment by martinkg** [comment]
sorry forgot to upload miam-player.desktop, changed description, please try again.
ok, **remotecontrol.patch** is obsolete, removed.

**Comment by martinkg** [comment]
added the following patch, but that doesn't solves the problem.

# cat -v acoustid.pro.patch 

```
--- Miam-Player-3654e7f973c6d3ec5e46ca77909b658ddecf5d32/src/acoustid/acoustid.pro.orig	2017-02-05 17:28:03.785450917 +0100
+++ Miam-Player-3654e7f973c6d3ec5e46ca77909b658ddecf5d32/src/acoustid/acoustid.pro	2017-02-05 17:29:17.869780421 +0100
@@ -49,6 +49,8 @@
 
 !macx {
     LIBS += -L$$OUT_PWD/../core/ -lmiam-core -ltag -lchromaprint
+    target.path = /usr/lib$$LIB_SUFFIX/
+    INSTALLS
 }
 macx {
     QMAKE_SONAME_PREFIX = @executable_path/../Frameworks
```

**Comment by MBach** [comment]
OK commit https://github.com/MBach/Miam-Player/commit/7b0d897aebbcccaf009ce150e27fc764d20970bd now should do the job!

**Comment by martinkg** [comment]
works now with the recent git commit.
Thanks
Martin
