### ISSUE TITLE
Where is the binaries?

### ISSUE THREAD

**Issue by hubuga** [MBach/Miam-Player#118]
I can't download the binaries cause the webpage is down and the release page only has the source code.

**Comment by hubuga** [comment]
Well, it seems that the problem is abandoned...

**Comment by mrkaban** [comment]
I join the question, where are the binary files? and why is the page removed from SourceForge?

**Comment by MBach** [comment]
You can the latest binary here: https://github.com/MBach/Miam-Player/releases/download/v0.9.0/MiamPlayer-0.9.0.exe

**Comment by mrkaban** [comment]
I beg you very much, do not delete any more binary files, as I link to them from my site.
