### ISSUE TITLE
Seek Slider needs to be completely filled

### ISSUE THREAD

**Issue by MBach** [MBach/Miam-Player#14]
Context:
- The seek slider in the main window is not fully filled at both sides

Expected:
- A full gradient, not only for the "inner" slider

**Comment by Ilya87** [comment]
I can't manipulate music decoding position with seek slider in the main window. Only hotkeys are the solution.

**Comment by MBach** [comment]
On Arch:
* I cannot use mousewheel to go back / forward (it should)
* Same for left / right keys when seek slider has focus. Question: should it work in conjunctions with hotkeys?
* Click and drag the button is working
* Click inside the slider and not the button is working

**Comment by Ilya87** [comment]
I cannot use mousewheel to go back / forward (it should) - me too.

Same for left / right keys when seek slider has focus. Question: should it work in conjunctions with hotkeys? - Why not? More possibilities sometimes often then less.

Click and drag the button is working - Not for me (if you mean seek slider button in time line). After releasing button it returns to the place of current playback (not the place I dropped it).

Click inside the slider and not the button is working - Again not for me. After releasing mouse button seek slider button returns to the place of current playback (not the place I made a mouse click).

**Comment by Ilya87** [comment]
Maybe this info would be usefull (console output):
[00007f7db0c08488] ogg demux error: No selected seekable stream found
[0000000037c9c968] core input error: INPUT_CONTROL_SET_POSITION(_OFFSET) 3,1% failed

**Comment by MBach** [comment]
I have the same thing for OGG files. I don't know yet if it's a bug from Miam-Player or VLC-Qt because I can seek the exact same file in VLC Media Player.

**Comment by MBach** [comment]
Seeking through OGG files on Windows is fine for me: I think this may be a bug with linux libraries for decoding OGG. On Arch, Qt5 Multimedia backend requires 'GStreamer 0.10 bad' plugins: maybe this is the source of the problem?

**Comment by Ilya87** [comment]
Did you mean gstreamer0.10-base-plugins? Because this package depends on libvorbis.

With the command such gst-launch-0.10 filesrc location=~/111.ogg ! decodebin2 ! alsasink I can't decode ogg files at all.

Error: from element /GstPipeline:pipeline0/GstDecodeBin2:decodebin20/GstOggDemux:oggdemux0: Internal error of data stream.
Additional debug information:
gstoggdemux.c(4490): gst_ogg_demux_loop (): /GstPipeline:pipeline0/GstDecodeBin2:decodebin20/GstOggDemux:oggdemux0:
stream stopped, reason not-linked

Mp3 files are decoded, but with stutttering sound.

**Comment by MBach** [comment]
I thought that the stuttering sound was coming from my virtual machine but it's not :( VLC can read the same MP3 without any glitches, but not in Miam Player. Of course, everything is working perfectly on Windows. I didn't pay attention to multiple messages like this before:

`void MainWindow::mediaPlayerStateHasChanged(QMediaPlayer::State) QMediaPlayer::StoppedState
libvlc Media: "/home/mbach/Music/Air/1996 - Premiers symptomes/01 - Modular Mix.mp3" Local: true
MediaPlayer::createLocalConnections()::<lambda()> playing
void MainWindow::mediaPlayerStateHasChanged(QMediaPlayer::State) QMediaPlayer::PlayingState
MediaPlayer::createLocalConnections()::<lambda()> playing
MediaPlayer::createLocalConnections()::<lambda()> playing
MediaPlayer::createLocalConnections()::<lambda()> playing
MediaPlayer::createLocalConnections()::<lambda()> playing
MediaPlayer::createLocalConnections()::<lambda()> playing
MediaPlayer::createLocalConnections()::<lambda()> playing
MediaPlayer::createLocalConnections()::<lambda()> playing
MediaPlayer::createLocalConnections()::<lambda()> playing
MediaPlayer::createLocalConnections()::<lambda()> playing
MediaPlayer::createLocalConnections()::<lambda()> playing
MediaPlayer::createLocalConnections()::<lambda()> playing
MediaPlayer::createLocalConnections()::<lambda()> playing
MediaPlayer::createLocalConnections()::<lambda()> playing
VlcMediaPlayer::Buffered 100
MediaPlayer::createLocalConnections()::<lambda()> playing`

So I need to do a code review to restrict those multiple signals from being sent.

**Comment by Ilya87** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=745847
Miam-Player sholud use gst-launch-0.10 playbin2 uri=file:// - it is about ogg
Stuttering sound is caused by gstreamer.

**Comment by MBach** [comment]
https://github.com/MBach/Miam-Player/commit/08d918da810945c3fd62512e74d909489004bfdf seems ok for painting.
I think we can close this issue, stuttering sound is not related to Miam Player because it relies on third party plugins to decode sound. You can switch to VLC backend and drop GStreamer backend.

**Comment by Ilya87** [comment]
1 - How can I swich to VLC backend?
2 - Fully fullfilled means (see screenshot)
![screen2](https://cloud.githubusercontent.com/assets/1446573/6657093/92458716-cb51-11e4-80d3-a23b1af1d273.png)

**Comment by MBach** [comment]
That's strange ! On Windows the linear gradient fits perfectly with rounded control to seek in the file.

**Comment by MBach** [comment]
Ok, so try with https://github.com/MBach/Miam-Player/commit/5c9d8f37a3cba8e1eec2c93bcffdc3f3362470e1
About VLC backend, I think you just have to install `phonon-qt5-vlc`

**Comment by Ilya87** [comment]
Miam Player doesn't depend on phonon. It depends on qt5-multimedia (which in its turn depends on gstreamer-0.10 https://www.archlinux.org/packages/extra/x86_64/qt5-multimedia/) and libvlc-qt. I can remove all phonon* packages and Miam Player still will decodes sound. I use vlc 2.2-qt5 and libvlc-qt 0.10.

P.S. Yes, gradient is full now

**Comment by MBach** [comment]
I close this issue right now, seeking into files is for another specific (unix) thread. Main purpose of this issue was for painting.
