### ISSUE TITLE
Allow custom genres when editing tags

### ISSUE THREAD

**Issue by MBach** [MBach/Miam-Player#17]
When one is editing tags, custom genres should be extended with custom text. Actually, only classic genre list is working. When writing some text, nothing is saved into the metadata

**Comment by Ilya87** [comment]
In my case I can't save the year in mp3 files - I add year, press save button, close Tag editor and when open file again in tag editor - no year tag is displayed. In Kid-qt I see -1 tag for the year value after this.

**Comment by MBach** [comment]
I don't reproduce your issue ! I have changed year for one album and when I load these files in kid3-qt the new value is working.
Moreover, custom genre has been implemented in old commit, but I don't remember which one. Can we consider to close this issue?

**Comment by Ilya87** [comment]
Yes, fixed for mp3, not ogg. This Album's mess of symbols appeared instead of typed album title «200 по встречной» (without «»). And I still can't save year for ogg.

![screen](https://cloud.githubusercontent.com/assets/1446573/6746540/fb08f18e-ceda-11e4-93eb-8a455bbc9584.png)

**Comment by MBach** [comment]
I have tested with OGG (Vorbis comment) and it's working. I might need to test all other OGG tag encapsulation.
See TagLib documentation : 
![OGG hierarchy](http://taglib.github.io/api/classTagLib_1_1Ogg_1_1File__inherit__graph.png)

In fact, this piece of code might be a problem :

    } else if (suffix == "ogg" || suffix == "oga") {
        _file = new TagLib::Vorbis::File(fp);
        _fileType = OGG;
    } else {

Can you tell me that you have OGG files which in fact are Flac, Opus or Speex. If so, can you upload somewhere please? Same for APE files. APE deals with APE tags or ID3v1 (like MP3) tags.

**Comment by Ilya87** [comment]
https://yadi.sk/d/3M21TLR6fPpro

**Comment by MBach** [comment]
Ok so this issue has changed a little ! I am trying to finish release 0.7.1 first

**Comment by Ilya87** [comment]
I can now write even in Russian album name in ogg, but still - can't year.

**Comment by MBach** [comment]
Is this issue still valid or not?

**Comment by Ilya87** [comment]
Issue is solved.
