### ISSUE TITLE
Can't add track from Artist

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#22]
1 - Using the Artist/Album view I can't add to playlist tracks. For some files I can and for some - not
![screen](https://cloud.githubusercontent.com/assets/1446573/6489765/22447096-c2b2-11e4-897f-66011abeaff5.png)

2 - Can't go to Artist's name using letters on the right side of Library.

3 - (Maybe connected with first issue). When I add ogg file to the playlist using File explorer Miam Player writes in Playlist "Error reading artist", "Error reading title" while all tags are visible in tag editor. https://yadi.sk/d/jWlICSHSf262E For example Alabaster - Regorge.ogg

**Comment by MBach** [comment]
I have started to work on point 1 after I have downloaded your files. In fact, there was a minor problem for tracks with missing tags (like empty Album) : constraint integrity failed in my SQLite database.

About point 2, I am working on the Unique Library and I want to reuse the class called `JumpToWidget`. However, my first implementation was only for the library, which is based on [QTreeView](http://doc.qt.io/qt-5/qtreeview.html). I am trying to reuse this widget with a [QTableView](http://doc.qt.io/qt-5/qtableview.html). `JumpToWidget` was too tight with this Tree: some work has still to be done to make it more generic. 

Point 3 is not connected to point 1. All tracks with japanese characters (in the filename) are not parsed by Miam Player, but tracks with japanese tags are working. Playback is working in both cases but of course if should display tags and be stored in the database.

**Comment by Ilya87** [comment]
"All tracks with japanese characters (in the filename) are not parsed by Miam Player, but tracks with japanese tags are working"
No, 
![screen](https://cloud.githubusercontent.com/assets/1446573/6499596/110a70d4-c30f-11e4-905b-73e3fd1ffbfc.png)

I now found out that 3rd point is connected with implementation of tag reader (or most probably playlist implementation). When I drop files from built-in File explorer to the playlist - it randomly denies to show tags of some files: I dragged the same files to other opened playlists and amount of "Error reading artist"... errors was different and different tracks were not shown correctly.

**Comment by MBach** [comment]
First point should be ok now. Next two are more complicated.

**Comment by Ilya87** [comment]
The third point is now also solved. But new strange behavior is detected - I can find RoughSketch artist in Library, but can't find kenta-v.ez. or M-Project. Displaying tags and decoding this files from File explorer is Ok. 

P.S. Is it normal that decoding of current track stops if I delete another one from the same playlist?

**Comment by Ilya87** [comment]
Sorting question: russian artist БИ-2 (filename starts with БИ-2) is displayed in Various while Бетховен artist (filename starts with 01.Adagio molto) is displayed in Y-letter section. IMHO sorting is wrong.

**Comment by Ilya87** [comment]
Another sorting issue - if tracks from the same album don't have track № - they are displaying as tracks from different album
![screen1](https://cloud.githubusercontent.com/assets/1446573/6511813/3c4c5aac-c380-11e4-9c0b-1e12c3ab6dc3.png)

**Comment by MBach** [comment]
Multiple questions here :-) ! So:
* It is normal that you see tracks if File explorer but not in Library. These 2 components are very different. That's why you can drag & drop files from file explorer to playlist and "Error reading" appears.
* Playback should not stop when you remove files. Actually, it stops only when tracks are over the current playing one, it doesn't stop when it's under.
* Sorting is another problem! I have not tested Russian language for sorting. I am converting internally every string with [QRegularExpression](http://doc.qt.io/qt-5/qregularexpression.html)
* The last one is not an issue because it's possible for 2 differents artists to release the same name for an Album. It's unlikely but still possible. We could discuss this if I should automatically merge or not Albums with the same name. Artist Album has been created to regroup all artists when it's a remix.

You are doing a very good job of beta-tester!

**Comment by Ilya87** [comment]
«I can find RoughSketch artist in Library, but can't find kenta-v.ez. or M-Project»
Oh no. Before reporting bugs I should restart Miam Player simple library rescan doesn't do full database rebuild. Now I also see M-Project and kenta-v.ez. in Library,but Russian sorting is still an issue: БИ-2 (ogg) is still in Various (what is wrong - mp3 files with Russian tags and filenames are in right place), Бетховен now is in Z-letter part where Russian and Japan-named artists are.

"Actually, it stops only when tracks are over the current playing one, it doesn't stop when it's under."
You are right, but what is and end of this behaviour?

**Comment by Ilya87** [comment]
NOOOOO! The third point is resurrected! First of all, dragging tracks to playlist from library shows tag errors (see picture), AND Library doesn't see all tracks 13  - on screenshot just 10, after removing all MiamPlayer files and rescanning again 11 are visible in library and 13 files in File explorer (dragging them to playlist also causing errors in tags).
I'm sure about my files - I specially add Album tag with Kid-qt tag manager.
![screen](https://cloud.githubusercontent.com/assets/1446573/6541677/f1917bd4-c4ef-11e4-8c49-d6970b9146f8.png)

**Comment by MBach** [comment]
With "non exotic" characters in the path it seems OK. Encoding is really a difficult thing...
![non_exotic_characters](https://cloud.githubusercontent.com/assets/1532657/6545414/2eb52b0a-c586-11e4-8f26-b42ed92b6f90.png)
By the way, I am trying to display japanese characters on Miam Player but I am missing something. Every program that I have compiled with Qt don't have support for foreign language. So right now I don't have the exact same environnement to be able to reproduce your issue.

**Comment by Ilya87** [comment]
Since 41dc9d9931dcdf545c931245282263718447787b I can't reproduce the third point in part of Error reading tagname. But The library (and File explorer - but more rare) still don't see all files. Library can see only 9-11 of 13 tracks. In your case - fonts that support Japanese characters should be installed to the system.
![screen](https://cloud.githubusercontent.com/assets/1446573/6550886/818bdee0-c640-11e4-85b4-6cf34160a6f5.png)

**Comment by Ilya87** [comment]
The second part of issue is solved. As the third. Remains the part with missing tracks in library.

**Comment by MBach** [comment]
Try https://github.com/MBach/Miam-Player/commit/43322679e708701dffe4fdce648fd45e80939b91 (simple #ifdef ...)

**Comment by Ilya87** [comment]
Now the third part is returned and still 11 of 13 tracks are shown
![screen](https://cloud.githubusercontent.com/assets/1446573/6761268/53d716ec-cf62-11e4-8217-557af50d4fdf.png)

**Comment by MBach** [comment]
This commit is the right one (I hope): https://github.com/MBach/Miam-Player/commit/d4ef22e869eeb47df045d12fcfda978652d3505a

**Comment by Ilya87** [comment]
I can't believe to my eyes, but this issue is solved. But new regression is found out: the same album, all tracks of this album in the same folder, all tracks have track number, but different Artist
![screen](https://cloud.githubusercontent.com/assets/1446573/6985165/01d83092-da39-11e4-97c9-1529f1568fe5.png)

**Comment by MBach** [comment]
Well, it's the expected behaviour if Artist is different. That's why Artist Album ("ARTISTALBUM", "ARTIST ALBUM", etc) was created. It can group remixes under the same label. If your files don't have this attribute, it's difficult to find them. But the major problem with missing Artist Album tag is : it's not a standard at all!

However, it might be possible to regroup these files when conditions are met : 
* no Artist Album tag
* same folder
* and track number ordered in a good way, corresponding to the exact same number of files in the folder

If these conditions are not met, it can lead to unpredictable things. For example, if someone has his music collection under one single folder: would you group by Albums? Remember that 'Album' is not an absolute and unique key over the world.

**Comment by Ilya87** [comment]
Thank you for fast response! I simply hope for automagical way of grouping.

**Comment by Ilya87** [comment]
And I want to add new thing - Artist Album tag is not saved (at least for mp3) by Miam-Player. And is not read "album artist" tag after kid3-qt creates it.

**Comment by MBach** [comment]
I am quite confident that Album Artist field is working because I spent lots of time to parse MP3, Vorbis, FLAC, ... I will make more tests to see how Miam Player ans Kid3 handle this specific tag.

**Comment by MBach** [comment]
Right ! Should be good: https://github.com/MBach/Miam-Player/commit/fc45727666cf5f2c286953be43a48e847f0f6f67

**Comment by Ilya87** [comment]
Miam-Player now can set and see ALBUMARTIST tag, but I still can't see changes - my album is still a list of separate files (all files have track №, same ALBUMARTIST tag, same Album tag).
I use Album view of music library.
