### ISSUE TITLE
Wrong tag interpretation

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#24]
If mp3 or ogg file has -1 as year or track number Miam Player shows Year and Track number as
![screen1](https://cloud.githubusercontent.com/assets/1446573/6513802/b75b1aa4-c38e-11e4-90f1-bf8b41e54408.png)
![screen2](https://cloud.githubusercontent.com/assets/1446573/6513806/b9f7e918-c38e-11e4-90b1-0681e20cc6a9.png)

VERY HUGE VALUE!

**Comment by MBach** [comment]
It's a very simple issue: it's possible to write negative values but in tag class (TagLib::File::Tag) `track()` is an unsigned int (= no negative value). I have to check if track() returns an integer over INT_MAX which is 2 147 483 647.
