### ISSUE TITLE
Miam-Player doesn't save amount and order of columns in playlist

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#25]
After removing some columns (unputting a tick from their titles) of playlist and changing places of columns I exit from Miam-Player, but opening player againg doesn't restore my column pattern and column order in playlist.
Also creating new playlist doesn't use my column pattern. The default pattern is used.

**Comment by MBach** [comment]
The behaviour that you are suggesting is not implemented but it's a good idea. One problem however, suppose you have 2 playlists with 2 differents column order. 

What should be displayed when creating a new one? A solution might be to take the last active playlist and to copy its column order in the new one. What do you think of this idea?

**Comment by Ilya87** [comment]
«A solution might be to take the last active playlist and to copy its column order in the new one»
Yes, very good solution. And don't forget to make playlist save column order on exit and restore on load of Miam-Player.

**Comment by MBach** [comment]
Should be ok with commit https://github.com/MBach/Miam-Player/commit/232ffbde0d09dcd99bbed28aaaecdec3bc3d0c68

**Comment by Ilya87** [comment]
I saw a new column - TrackDAO that can't be removed (first run of updated version).
After restarting Miam-Player this column disappeared, but now column titles don't move with move of horizontal scrollbar.
![screen](https://cloud.githubusercontent.com/assets/1446573/6540465/1bc3c578-c4b0-11e4-8745-5383322994b0.png)

**Comment by MBach** [comment]
Move header when scrolling: https://github.com/MBach/Miam-Player/commit/496a840033f8d95bc06b0869823181f3e3a00bb2
Hide permanently column TrackDAO: https://github.com/MBach/Miam-Player/commit/1ae75897fa1bb647594b2beda8bcb36d42629f42

**Comment by Ilya87** [comment]
"Hide permanently column TrackDAO" - NO. Should I delete all Miam-Player settings and database?
![screenshot-2944a45d](https://cloud.githubusercontent.com/assets/1446573/6541549/e82ff15c-c4e9-11e4-9328-c7e05f52e405.png)

**Comment by MBach** [comment]
It's not required to delete database (in `~/.local/share/MmeMiamMiam/MiamPlayer/mp.db`) but column settings are stored in `~/.config/MmeMiamMiam/MiamPlayer.conf`

You must delete this file if you want to have a clean Player.

**Comment by Ilya87** [comment]
P.S. For newly created playlist TrackDAO column is not visible. Patch works.
