### ISSUE TITLE
Disabling alternative colors for playlist doesn't disable them

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#26]
In my opinion user should be able to choose colors for playlist and player separately (maybe as it was intended to). Now, when I select No answer to the question «Would you like to alternate colors in playlists?» and change colors of player - colors of playlist are changing together with colors of player.
![screen](https://cloud.githubusercontent.com/assets/1446573/6540708/3c58672c-c4be-11e4-9b1d-a67a36a0f475.png)

**Comment by MBach** [comment]
In fact, alternate colors are working but you need to create a new playlist. Current one isn't modified. Yes, it should be improved because I don't like programs when you have to open/close once again to see changes :)

**Comment by Ilya87** [comment]
Maybe I miss something, but for version 1ae75897fa1bb647594b2beda8bcb36d42629f42 colours are changing instantly, but my bug report was about another issue:

when I answer NO to the question «Would you like to alternate colors in playlists?» AND YES to question «Would you like to alternate colors of player?» - changing the color (Background for playlist and library) changes color of playlist and library inspite of I answer NO to the question «Would you like to alternate colors in playlists?». This means answering to the question DOES NOTHING.

My idea was that the right solution is to create two independent alternate color options - one for library and another for playlist. Hope it's not difficult.

**Comment by MBach** [comment]
Hmm I see what you mean but unfortunately, it will be difficult to have 2 separate colors for library and playlists. This part is quite experimental and it requires a lot of effort to make a consistent theme automatically (switching text color to white when it's too dark).

About alternate color, it's like Qt says:
> QPalette::Base : Used mostly as the background color for text entry widgets, but can also be used for other painting - such as the background of combobox drop down lists and toolbar handles. It is usually white or another light color.
> QPalette::AlternateBase : Used as the alternate background color in views with alternating row colors (see QAbstractItemView::setAlternatingRowColors()).

So when you're using default colors, it's gray for odd rows and light gray or white for even rows

**Comment by Ilya87** [comment]
Thank you! Now I understand what does term «alternate» in this case means. It helped me in translation of Miam-Player (wait for Russian translation PR in few days I hope).

**Comment by MBach** [comment]
By the way, when checking if this issue was still valid or not, I found a minor issue for first playlist. Now it seems to be good for me, can you please confirm that alternate color can be toggled at runtime and close this one?
Fixed with: https://github.com/MBach/Miam-Player/commit/947e591f5156e7cc5fd6bc7695e5d7d5bfdce362

**Comment by Ilya87** [comment]
I see colors of playlist and library are changing at real time.
