### ISSUE TITLE
Using an option to ignore the definite article "the" doesn't work

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#28]
Using an option to ignore the definite article "the" doesn't work, in my Library I see The Cranberries as The Cranberries, even if I type «The» to the field below the mentioned option.

**Comment by MBach** [comment]
I'm aware of this: I have made some changes to reduce duplicate code with TagConverter. But I have also introduced some bugs that I need to work on!

**Comment by MBach** [comment]
This should be better now!
https://github.com/MBach/Miam-Player/commit/193d6d833d0eb901ed4ecfe66af0c16468cdd7a0

**Comment by Ilya87** [comment]
Still doesn't work (yes, I removed old config directories before test). And still artists without Latin letters in name (Russian for example) aren't in an alphabetical order - they are even messed with kana-named artists.

**Comment by MBach** [comment]
So if I understand, it's working for Latin letters! Maybe you should open a new issue with what you get and what you would like to have for Russian or Japanese bands.

**Comment by Ilya87** [comment]
I also have in my library music tracks with artists with «the» at the beginning - your patch doesn't work for them. If you are talking about new issue for alphabetical sorting disorder - yes, I'll open a new one.

**Comment by Ilya87** [comment]
I missed important info - I should write an article by myself into the field (I forgot about it) - in this case your commit works. Closing issue.
