### ISSUE TITLE
Save and load playlist function is broken since new commits

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#29]
1 - Remove saved playlists in Playlist manager.
2 - Create 2 playlists with different tracks
3 - Turn on options - save playlists in memory and load them on program start
4 - Restart Miam-Player
Result - All the tracks from 2 playlists are in one playlist, second playlist even doesn't appear in playlist tab bar.

**Comment by MBach** [comment]
Try https://github.com/MBach/Miam-Player/commit/f86cba5b7949bd9adbeff57cbb81a4f140b31c24
For other bugs (will you find them :) ?) about "playlists color icons" and "ask for save" unmodified playlists do not open issue yet!
