### ISSUE TITLE
Change default folder for file explorer

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#31]
I think this is easy issue. Now File Explorer sets default folder for music - my system's default path for music. But it If I have another music path and only one folder for music (in Library settings) - File Explorer should set this directory as default automatically. Or another solution - let user decide which default directory should be used.

**Comment by MBach** [comment]
Done in https://github.com/MBach/Miam-Player/commit/08d918da810945c3fd62512e74d909489004bfdf

**Comment by Ilya87** [comment]
Thank you very much!

**Comment by MBach** [comment]
Picture: ![default music folder](https://cloud.githubusercontent.com/assets/1532657/6657029/7683ddb0-cb3e-11e4-8aae-6ddbd8452964.png)

If the File Explorer tab is active, you can see immediately when you're switching to an item to another.

**Comment by Ilya87** [comment]
Yes, I already tested new build - it's easy with linux.
