### ISSUE TITLE
No sound after 08d918da810945c3fd62512e74d909489004bfdf

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#32]
I seek ogg track using hotkey, after that  - the sound disappears
![screen](https://cloud.githubusercontent.com/assets/1446573/6657116/5aef5ce6-cb52-11e4-9537-6547718e29ed.png)

**Comment by Ilya87** [comment]
After deleting lines with setVolume(0); sound appeared again in 08d918da810945c3fd62512e74d909489004bfdf
![screenshot-6525e5d4](https://cloud.githubusercontent.com/assets/1446573/6880592/45fa4f50-d54b-11e4-92ed-1e25f771ee99.png)

**Comment by MBach** [comment]
Ok so I think it's much better now! https://github.com/MBach/Miam-Player/commit/f3439926a22be03acde273ff818035a2ed1eda41

**Comment by Ilya87** [comment]
It works! Thank you very much for that!
