### ISSUE TITLE
Drag and drop tracks from built-in File Explorer leads to file mix

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#36]
1 - Drag and drop folder with only files that have same name but different track № in filename from File Explorer to playlist (smth. like Artist - Track01.ogg, Artist - Track02.ogg)
2 - Their names will not be in normal order in playlist.
![screenshot-c7d183ea](https://cloud.githubusercontent.com/assets/1446573/7010860/323fd160-dcad-11e4-80f3-21020527ab59.png)

**Comment by MBach** [comment]
A simple sorting should do the job: https://github.com/MBach/Miam-Player/commit/207f4b187d162265a327ac69bf45da84b30c7557
