### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by ntadej** [MBach/Miam-Player#42]
I managed to build Miam Player (master) for OS X, but it works strangely. Main window is constantly expanding.

Do you need any help building it for OS X?

**Comment by MBach** [comment]
I know, I have the same behaviour! Since I didn't have much request for a OS X build, I did not referenced this issue yet. I will look for it and finally try to make a build. Last time, I had trouble to build vlc and vlc-qt from sources...

**Comment by MBach** [comment]
Alright so OS X packaging is much better now. I have found the issue about expanding MainWindow. I have to redesign how the left pane header is painted in [ExtendedTabBar class](https://github.com/MBach/Miam-Player/blob/master/code/MiamPlayer/library/extendedtabbar.cpp)

OS X support seems good for me, but lot of painting needs to be adapted for Mac. 

To build from scratch: pay attention to link with VLC_PLUGIN_PATH (globally or only in Qt Creator)
To create a bundle: I made a [script](https://github.com/MBach/Miam-Player/blob/master/packaging/osx/create_osx_bundle.sh) which calls macdeployqt in [packaging/osx/](https://github.com/MBach/Miam-Player/tree/master/packaging/osx): an .app and a .dmg are created and they seem to work for me.

Could you please check if [MiamPlayer-0.7.1.dmg]() is working on your computer?
