### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#47]
e3a9b version, clang 3.6:
Error while building

library/librarytreeview.cpp:30:32: error: taking the address of a temporary object of
      type 'QMultiHash<SeparatorItem *, QModelIndex>' [-Waddress-of-temporary]
        _proxyModel->setTopLevelItems(&_libraryModel->topLevelItems());
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7 warnings and 1 error generated.

**Comment by MBach** [comment]
Indeed ... QMap is [implicitly shared](http://doc.qt.io/qt-5/implicit-sharing.html) so I just need to pass it as a const reference!

**Comment by MBach** [comment]
Should be fixed with https://github.com/MBach/Miam-Player/commit/a78584d336c59ef2a5bc81b13b464e28805e5ffe
