### ISSUE TITLE
Can't add artist's track without album's tag to playlist

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#48]
Version of Miam-Player a78584d336c59ef2a5bc81b13b464e28805e5ffe
My view - Library Artist\Albums
Can't add artist's track without album's tag to playlist or playback them with this view.

**Comment by MBach** [comment]
A minor regression was introduced in last commit... https://github.com/MBach/Miam-Player/commit/f6aa7827ca2e356d7e46ba934b0a1bb7588ff60d should be better.
