### ISSUE TITLE
Challenge: create a new Application Icon!

### ISSUE THREAD

**Issue by MBach** [MBach/Miam-Player#51]
Miam-Player needs a new application icon.
Current one isn't so great ...
If anyone has some skills in design, please feel free to help :)

On OSX, we have this:
![icon](https://cloud.githubusercontent.com/assets/1532657/7755526/039f9686-fff5-11e4-880e-c8df0d181398.png)

**Theme**: Baking, food, sweets, Yum-Yum (Miam is French for Yum)

Requirements:
- SVG
- Few colors, not from a real-world photo

That's all: it can contains gradients, or be in flat design!

**Comment by Ilya87** [comment]
https://yadi.sk/d/7Q7u_eHlgnxpb - In Inkscape I selected 255 in background properties, so it should be white, but my viewers see this background as transparent.
![miam-challenge](https://cloud.githubusercontent.com/assets/1446573/7758749/acfde31c-0014-11e5-8889-79e4c3f3d151.png)

**Comment by MBach** [comment]
Thank you for this first proposal :+1: I'll try to modify yours to post here some variants.

**Comment by MBach** [comment]
A first try from your work:
![miam-challenge2](https://cloud.githubusercontent.com/assets/1532657/7781007/04765886-00e7-11e5-9d86-421d1ca4333f.png)
http://www.miam-player.org/images/work-in-progress/mbach_miam-challenge.svg

**Comment by Ilya87** [comment]
What about another background
![mbach_miam-challenge](https://cloud.githubusercontent.com/assets/1446573/7792486/9121a7ce-02bb-11e5-9f9c-41266a38929f.png)
 color?

**Comment by MBach** [comment]
Not bad! I can see you're not a big fan of purple ;)

But I would love to see new designs, not from picture converted to svg. It's like a "bottle thrown into the sea"

**Comment by MBach** [comment]
What about the [G-clef](https://en.wikipedia.org/wiki/Clef) mixed with Candy Cane?
![g-clef](https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/GClef.svg/87px-GClef.svg.png)
![candy-cane](http://www.setthings.com/wp-content/uploads/2015/12/Candy-Cane-Classic-182x300.jpg)

- The bottom could be in gradient with white & red pattern
- Or the "circular" pattern white & red could be applied to the whole Clef
