### ISSUE TITLE
Remove precompiled libraries, binaries or vcredist from source repo

### ISSUE THREAD

**Issue by akien-mga** [MBach/Miam-Player#55]
The current source repo contains lots of binaries that are not directly relevant to Miam-Player and its source code, but are I suppose bundled for convenience:
* lib/ (72 MB)
* packaging/ubuntu/miam-player-0.7.0.run (25 MB)
* packaging/windows/vcredist/ (14 MB)

When removing those, the source tarball goes from 120 MB to 11 MB (!), which is an important difference especially for Linux distro packagers.

Another argument against putting binaries in a git repo is that your git repo becomes *huge*, since git can't produce diffs for binary content, so each new revision of a given binary file adds its whole size to the git repo. As a consequence of this, cloning the Miam-Player repo requires downloading 150 MB of data, and the decompress repo is 268 MB – I suppose it would be way more if you updated the binaries often.

I do understand though that having those in the repo may be convenient, especially for Windows developers where installing development libraries is relatively harder than on Linux distros (unless the said libraries are not packaged system-wide). Maybe an alternative could be to put these binaries in a FTP, and have a script that downloads them locally?

**Comment by MBach** [comment]
That's a good point but it won't be possible for a Windows user – like me – to clone repository, click on build & run, and everything goes on!

If you can suggest a way to improve this, or pointing tools to download files automatically without too much pain (I have a ftp which hosts binaires), it could be great.

Maybe it's possible to download extra libs at first compilation on a FTP with other tools than qmake: cmake, qbs, others?

**Comment by MBach** [comment]
By the way, I have deleted file `packaging/ubuntu/miam-player-0.7.0.run`

**Comment by akien-mga** [comment]
> If you can suggest a way to improve this, or pointing tools to download files automatically without too much pain (I have a ftp which hosts binaires), it could be great.

On Linux a bash script would do the script, but I don't know much about download files on Windows. I've done a quick research and many people speak about PowerShell, which is a built-in component of Windows since Vista, and has functions like Invoke-WebRequest [1] to retrieve data via HTTP/FTP.

[1] https://technet.microsoft.com/en-us/library/hh849901
