### ISSUE TITLE
Micro Browser shows white screen when clicking on "Open Connection Popup" when using the Deezer plugin

### ISSUE THREAD

**Issue by donmega** [MBach/Miam-Player#56]
Micro browser shows a white popup when trying to authenticate Deezer:

Screenshot:
http://i.imgur.com/ZdgzR2m.png

Debug Log:
http://i.imgur.com/WpYvc3x.png

Windows 7 X64

Lemme know if you need more info :)

**Comment by MBach** [comment]
Hi,
You need to install the latest OpenSSL release to be able to communicate with Deezer' servers.

**Comment by donmega** [comment]
Thx for the fast reply!

I've installed the latest OpenSSL, and i am still getting a white screen.
Here is the debug log:

http://i.imgur.com/bDMDWGJ.png

**Comment by donmega** [comment]
I've tried it also on another system, and this is the output on that system (OpenSSL 1.02d):

http://i.imgur.com/DGRweAn.png

**Comment by MBach** [comment]
Well it should work with OpenSSL 64 bits... On the first screen you've posted, the output log doesn't show very useful informations. So we can assume it's working ? Did it display the login page from Deezer ?

**Comment by donmega** [comment]
Hi,

Still getting a white screen on both systems :(. I've tried OpenSSL 64 bit, same problem :(.

**Comment by MBach** [comment]
I don't understand because if I look on the stats provided by the Deezer's API:
![permission_box](https://cloud.githubusercontent.com/assets/1532657/8916416/a2ffab18-34ab-11e5-828d-234665ff9631.png)
I can see that one permission box was shown and accepted by user (probably you?). I will try to investigate but I have few inputs so it will be very hard to find why it's not working.

**Comment by donmega** [comment]
Hi,

I didn't get the permission box. Here is a video of how it looks like on my system:
https://www.wetransfer.com/downloads/603f2edd1e7c1476e50e56bc3b5d6e7820150729072543/4d3f8d49e696f779d91681632aead3f220150729072543/d77f65

Thank you for looking into it :)

**Comment by donmega** [comment]
Here is a video of my second system:
https://www.wetransfer.com/downloads/2f67eca0a10688f6456e8a63c9da0faf20150729080809/19826b4e5bf03bbc1c97e48cb2feba1b20150729080809/bf9707

**Comment by donmega** [comment]
Getting some new errors now. I've removed part of the token to encrypted:

Warning: void __cdecl UniqueLibrary::init(void)
Warning: void __cdecl MediaPlayer::setVolume(int) couldn't set volume to 90
Warning: void __cdecl SqlDatabase::load(void) QObject(0x0) 
Warning: void __cdecl SqlDatabase::loadFromFileDB(bool) true
Warning: void __cdecl TableView::setViewportMargins(int,int,int,int)
Warning: loadFinished
Warning: void __cdecl DeezerPlugin::login(void)
Warning: void __cdecl DeezerPlugin::login(void)
Warning: void __cdecl UniqueLibrary::setVisible(bool) true
Warning: hh QHeaderView(0x3539510)
Warning: void __cdecl SqlDatabase::load(void) QObject(0x0) 
Warning: void __cdecl SqlDatabase::loadFromFileDB(bool) true
Warning: void __cdecl TableView::setViewportMargins(int,int,int,int)
Warning: void __cdecl UniqueLibrary::setVisible(bool) false
Warning: void __cdecl DeezerPlugin::login(void)
Warning: void __cdecl DeezerPlugin::login(void)
Warning: Unknown reply. Code: 499 String: "Error downloading http://www.miam-player.org/deezer-micro/channel.html#access_token=ENCRYPTEDvoR6bR55b88c2cc89b29tF4iin&expires=1574 - server replied: Server Hangup"
Warning: Reply url:   QUrl( "http://www.miam-player.org/deezer-micro/channel.html#access_token=ENCRYPTEDvoR6bR55b88c2cc89b29tF4iin&expires=1574" )  , requested url  QUrl( "http://www.miam-player.org/deezer-micro/channel.html#access_token=ENCRYPTEDvoR6bR55b88c2cc89b29tF4iin&expires=1574" ) 
Warning: Unknown reply. Code: 499 String: "Error downloading http://www.miam-player.org/deezer-micro/channel.html#access_token=ENCRYPTEDvoR6bR55b88c2cc89b29tF4iin&expires=1562 - server replied: Server Hangup"
Warning: Reply url:   QUrl( "http://www.miam-player.org/deezer-micro/channel.html#access_token=ENCRYPTEDvoR6bR55b88c2cc89b29tF4iin&expires=1562" )  , requested url  QUrl( "http://www.miam-player.org/deezer-micro/channel.html#access_token=ENCRYPTEDvoR6bR55b88c2cc89b29tF4iin&expires=1562" ) 
Warning: Unknown reply. Code: 499 String: "Error downloading http://www.miam-player.org/deezer-micro/channel.html#access_token=ENCRYPTEDvoR6bR55b88c2cc89b29tF4iin&expires=1562 - server replied: Server Hangup"
Warning: Reply url:   QUrl( "http://www.miam-player.org/deezer-micro/channel.html#access_token=ENCRYPTEDvoR6bR55b88c2cc89b29tF4iin&expires=1562" )  , requested url  QUrl( "http://www.miam-player.org/deezer-micro/channel.html#access_token=ENCRYPTEDvoR6bR55b88c2cc89b29tF4iin&expires=1562" ) 
Warning: initial url
Warning: Received finished signal while progress is still: 10 Url:  QUrl( "https://connect.deezer.com/oauth/auth.php?app_id=141475&redirect_uri=http://www.miam-player.org/deezer-micro/channel.html&response_type=token&scope=manage_library,basic_access" )

**Comment by FromScratchGDN** [comment]
After removing Miam-player from "My Applications" in deezer, and re-authenticating Miam-Player, it's working :). You can close this issue :)
