### ISSUE TITLE
d8c342ba23 failed to link library at building

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#58]
I get an error
/usr/bin/ld: release/.obj/equalizerdalog.o: undefined reference to symbol «_ZN12VlcEqualizer10setEnabledEb»
/usr/lib/libvlc-qt-core.so.0.11: error adding symbols: DSO missing from command line

libvlc-qt - latest git, vlc - 2.2.1

**Comment by MBach** [comment]
Done in https://github.com/MBach/Miam-Player/commit/4ae4bc31a387bc5a67326abf32ca7057b998bd7f
I didn't have the time to compile on Arch that you've already opened an issue :)!
Next release with Equalizer is almost finished.
