### ISSUE TITLE
QtAV linking error

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#61]
When I use QtAV from git - (the build script - http://pastebin.com/pjE9Hcy8). Compilation fails with message that -lQt5AV not found.

When I change  
```LIBS += -L$$OUT_PWD -L/usr/lib/x86_64-linux-gnu/ -ltag -lQt5AV```
to
```LIBS += -L$$OUT_PWD -L/usr/lib/x86_64-linux-gnu/ -ltag -lQtAV```
in MiamCore.pro, Miam-Player compiles, but can't play any file.

**Comment by MBach** [comment]
Well there's a little problem with the name of the Shared Library, but it's playing music here:
![miam-player_playing](https://cloud.githubusercontent.com/assets/1532657/9474565/b9d5faa0-4b61-11e5-87e5-23f8fec34a49.png)

**Comment by MBach** [comment]
The debug output:

    Warning: void UniqueLibrary::init()
    Warning: MusicSearchEngine::MusicSearchEngine(QObject*)
    Warning: void MusicSearchEngine::setWatchForChanges(bool) true false
    Warning: void SqlDatabase::load() QObject(0x0)
    Warning: void SqlDatabase::loadFromFileDB(bool) true
    Warning: QtAV::AVPlayer::mediaStatusChanged LoadedMedia
    Warning: paused
    Warning: void MediaPlayer::pause()

**Comment by Ilya87** [comment]
Maybe my build script isn't right, but even QMLPlayer can't play audio - video only. But I do all right.

**Comment by wang-bin** [comment]
The library name `Qt5AV` is only for Qt5.4.x. For all other versions it should be `QtAV`. I use a qmake function to generate the name, but the function is broken in Qt5.4 and was fixed in Qt5.5

**Comment by wang-bin** [comment]
@Ilya87 set environment var `export QTAV_LOG=all` to show the log

**Comment by Ilya87** [comment]
@wang-bin QTAV_LOG=all - QtAV searches Pulseaudio which I obviously doesn't have. I have OpenAL instead http://pastebin.com/Gd1yCnVq, but after Pulseaudio not initialized QtAV stops searching other engines.

**Comment by MBach** [comment]
Ok so I can change in my *.pro file with latest release: ```-lQtAV``` @wang-bin 

Can we consider this issue as resolved?

**Comment by Ilya87** [comment]
Yes, but the last question - can you create an option to use openal audio instead of Pulseaudio? Because I have no sound due to this issue imo.

**Comment by MBach** [comment]
I don't know exactly how QtAV works!

I want to drop VLC-Qt library because I have started a plugin which incorporate AcoustID / Chromaprint (and relies on FFMPEG, also used by QtAV). 

https://github.com/MBach/acoustid-plugin

**Comment by wang-bin** [comment]
@Ilya87 you can remove `<< QStringLiteral("Pulse")` in AudioOutput.cpp. There's no  qml api to change audio.

**Comment by Ilya87** [comment]
@wang-bin Thank you! This fixed the problem!

**Comment by MBach** [comment]
@wang-bin I don't use QML in my project. I can notice that I can use ```QtAV::AudioOutput::backendsAvailable()``` function (and others).

Do you think it's a good idea to create a small config dialog with all backends available and ask one to chose one explicitly? You could imagine a QComboBox for example. What I propose is already implemented in VLC:
![vlc_audio_output](https://cloud.githubusercontent.com/assets/1532657/9533249/04f892bc-4d11-11e5-90ae-7c835bf90b86.png)

**Comment by wang-bin** [comment]
You can use `AudioOutput::setBackends(backends_list)`. For example, `ao->setBackends(QStringList() << "OpenAL" << "PulseAudio")` will try to initialize OpenAL. If It fails, try PulseAudio. There are some issues not fixed in PulseAudio. OpenAL is enough.
