### ISSUE TITLE
How to play music from Deezer?

### ISSUE THREAD

**Issue by FromScratchGDN** [MBach/Miam-Player#64]
Hi,

Local music is working, and i can also connect to Deezer. But when i try to play music from Deezer (I have an Premium subscription), it's not playing.

Log:
DeezerWebPlayer::play(const class QUrl &)  QUrl( "http://www.deezer.com/track/7753720" ) 
Warning: void __cdecl DeezerWebPlayer::play(const class QUrl &)  QUrl( "http://www.deezer.com/track/7753720" ) 
Warning: void __cdecl DeezerWebPlayer::play(const class QUrl &)  QUrl( "http://www.deezer.com/track/7753720" ) 
Warning: void __cdecl DeezerWebPlayer::play(const class QUrl &)  QUrl( "http://www.deezer.com/track/7753718" ) 
Warning: void __cdecl DeezerWebPlayer::play(const class QUrl &)  QUrl( "http://www.deezer.com/track/7753718" ) 
Warning: void __cdecl DeezerWebPlayer::play(const class QUrl &)  QUrl( "http://www.deezer.com/track/7753717" ) 
Warning: void __cdecl 

Btw: Using the Windows version

**Comment by MBach** [comment]
Hello,

Could you check that you have:
* Flash Player installed
* OpenSSL installed
* That you are logged in to Deezer
* You have files in ```C:\Users\<you>\AppData\Local\MmeMiamMiam\MiamPlayer\``` other than ```mp.db```, like Cache folder.

**Comment by MBach** [comment]
Moving this issue to https://github.com/MBach/deezer-plugin
