### ISSUE TITLE
Segmentation fault on start

### ISSUE THREAD

**Issue by nsirolli** [MBach/Miam-Player#67]
Hi,

I have installed Miam-Player for openSUSE (from the Packman repositories), and when starting Miam-Player from a terminal, I'm getting a segmentation fault message; in particular, Miam-Player does not start.

Please let me know if I can help you to debug this.

**Comment by MBach** [comment]
Hi @nsirolli,
It's been a long time that I didn't checked on openSUSE, but a few days ago it seems to work fine on Ubuntu. I'm finishing a new release (0.8.0) and lots of changes were made. For example, I don't use libVLC anymore and I've switched to [libQtAV](https://github.com/wang-bin/QtAV).
About the segfault on start, I'll try to reproduce it on my VM.

**Comment by nsirolli** [comment]
Great, I'll wait for 0.8.0. BTW, I'm using openSUSE Leap 42.1.

**Comment by Ilya87** [comment]
The first step to solve the problem is to publish gdb backtrace of debug build.

**Comment by MBach** [comment]
As @Ilya87 said, please provide a backtrace or steps to reproduce the bug. @nsirolli

**Comment by nsirolli** [comment]
I'm sorry for the delay. In these days I'm away from my computer. But,
after updating my system some weeks ago, Miam player started working. I
guess I can no longer provide you interesting information.

**Comment by Ilya87** [comment]
@nsirolli, in your case the issue should be closed. You can use Close button at the bottom of thread.
