### ISSUE TITLE
Cannot browse network folder

### ISSUE THREAD

**Issue by domlysz** [MBach/Miam-Player#68]
Hi,

I have installed Miam 0.73 on windows 10. I search for a simple cross platform audio player that can acces music as file browser, so this soft seems great ! 

But there is no way to access a network folder, I try to make a shortcut on the desktop for help Miam accessing the folder. It seems I can navigate throught the folder tree with url buttons on the top but Miam just can't scan the content of the folder.

Hope it's help to improve Miam.

**Comment by domlysz** [comment]
Finally I just mapped the network folder to a drive letter and it works. Browsing folder is little slow but functional.

**Comment by MBach** [comment]
Hi @domlysz,
Thank you for pointing out this problem about network folders. I don't know if it's possible to browse them with Qt Framework for Windows, without breaking the build for other OS like Ubuntu or OSX.

**Comment by MBach** [comment]
Cannot be done in cross platform way. Please @domlysz, open a new issue in this repository dedicated to Windows specific features: https://github.com/MBach/windows-toolbar
