### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#74]
In Library mode the library text stays English in spite of existing Russian translation:
![screenwe1](https://cloud.githubusercontent.com/assets/1446573/12695278/6e38f12c-c75a-11e5-8ad5-86f7b465f3f6.png)

![screenwe2](https://cloud.githubusercontent.com/assets/1446573/12695280/738d3e62-c75a-11e5-8e85-3ff1ec4ca145.png)

**Comment by Ilya87** [comment]
P.S. common is write for English, not commun. (Sequential mode is the most commun mode to play tracks in a playlist. It will play tracks from Top to Bottom.)

**Comment by MBach** [comment]
Indeed! Because commun is a French word, and is the direct translation of common.

**Comment by MBach** [comment]
Ok it should be fixed, I think.

**Comment by Ilya87** [comment]
The word Years is missing.
![screenwe1](https://cloud.githubusercontent.com/assets/1446573/12791090/8873a424-cab6-11e5-8cbd-cd05a1e0e891.png)
![screenwe2](https://cloud.githubusercontent.com/assets/1446573/12791091/888a652e-cab6-11e5-8159-e4e85f7277b2.png)

**Comment by MBach** [comment]
I don't know why the attribute "don't translate" was set on this particular field, but I removed it.
