### ISSUE TITLE
support LIB_SUFFIX

### ISSUE THREAD

**Issue by martinkg** [MBach/Miam-Player#78]
Add LIB_SUFFIX cmake convention to support fedora/redhat-style multilib, instead of hard-coding path
target.path = /usr/lib/

Long-term, probably ought to consider using something like
https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html
instead
[miam-player-0.9.0-libsuffix.patch.txt](https://github.com/MBach/Miam-Player/files/117692/miam-player-0.9.0-libsuffix.patch.txt)

**Comment by MBach** [comment]
Hi @martinkg 

I'm sorry but I don't get it. Currently, cmake build system isn't supported (I'm using qmake). The patch you have written is to make the *.pro files compatible with cmake?

**Comment by martinkg** [comment]
Hi @MBach 
thanks for your feedback.
Sorry for my false information, i use of course qmake too.

I' am working on a review of the miam-player package for the rpm based distribution Fedora.
I' am using the following rpm spec file to build a rpm package, you can see:
https://martinkg.fedorapeople.org/Review/SPECS/miam-player.spec

the package use in the build section the macro %{_qt5_qmake}
%build
%{_qt5_qmake} \
    QMAKE_CFLAGS="%optflags" \
    QMAKE_CXXFLAGS="%optflags" \
    LIB_SUFFIX="$(echo %_lib | cut -b4-)"
make %{?_smp_mflags}
.....

the macro uses the command /usr/lib64/qt5/bin/qmake as you can see.
# rpm -E "%{_qt5_qmake}"
output: /usr/lib64/qt5/bin/qmake

**Comment by MBach** [comment]
Ok I see... I was on the wrong path with the first link you provided which is hosted on cmake.org. So, I have understand your diff patch, I have just to append ```$$LIB_SUFFIX``` after ```lib```

**Comment by martinkg** [comment]
yes, that's correct, thanks for changing in github.

**Comment by MBach** [comment]
Check this out : https://github.com/MBach/Miam-Player/commit/c552b40b18411fb8fdb18032ab9966460660be5e

**Comment by MBach** [comment]
By the way, Miam-Player doesn't require VLC-Qt anymore:

```
BuildRequires:  pkgconfig(libVLCQtCore)
BuildRequires:  pkgconfig(libVLCQtQml)
BuildRequires:  pkgconfig(libVLCQtWidgets)
```

I have switched to [QtAV](https://github.com/wang-bin/QtAV)

**Comment by martinkg** [comment]
thanks for your info, rpm spec file was updated
Spec URL: https://martinkg.fedorapeople.org/Review/SPECS/miam-player.spec

**Comment by akien-mga** [comment]
I guess the issue could be considered as closed. I'd just like to note that though ``LIB_SUFFIX`` is indeed the conventional variable for **CMake** (as erroneously mentioned in OP), for **qmake** it seems that ``libsuff`` is more widespread.

At least my distro Mageia defines its ``%qmake_qt5`` macro as:
```
qmake_qt5  
  %{_qt5_bindir}/qmake \
  %if "%{_lib}" != "lib" 
     libsuff=64 \
  %endif 
  QMAKE_CFLAGS="${CFLAGS:-%optflags}" \
  QMAKE_CXXFLAGS="${CXXFLAGS:-%optflags}" \
  QMAKE_LFLAGS="%{?ldflags}" \
  QMAKE_STRIP=
```
and it works perfectly for most Qt 5 packages.
