### ISSUE TITLE
Game_Music_Emu support

### ISSUE THREAD

**Issue by Oggom** [MBach/Miam-Player#8]
Would it be possible to implement Game_Music_Emu into Miam Player?

It's an audio library that adds support for various older video game system sound formats:

http://www.slack.net/~ant/libs/audio.html#Game_Music_Emu

**Comment by MBach** [comment]
Game Music Emu support is working:
![gme](https://cloud.githubusercontent.com/assets/1532657/6547406/414b35ba-c5d7-11e4-9175-980a85d3f32c.png)

**Comment by Oggom** [comment]
Nice! Thank you very much :+1:
