### ISSUE TITLE
miam-player.appdata.xml AppData file for GNOME-Software Center - Enhancement

### ISSUE THREAD

**Issue by martinkg** [MBach/Miam-Player#81]
can you please add the attached AppData file to miam-player, to register as an application to be visible in the GNOME software center. (https://fedoraproject.org/wiki/User:Rhughes/DraftAppDataGuidelines )
miam-player.appdata.xml AppData file: (please rename miam-player.appdata.xml.txt to miam-player.appdata.xml).
[miam-player.appdata.xml.txt](https://github.com/MBach/Miam-Player/files/118938/miam-player.appdata.xml.txt)

**Comment by MBach** [comment]
Hello @martinkg 
Where should I put this file? Into ```Miam-Player/fedora/miam-player.appdata.xml``` for instance? If so, I also should modify ```Miam-Player/src/Player/Player.pro``` file with:

    unix:!macx {
        target.path = /usr/bin
        desktop.path = /usr/share/applications
        desktop.files = $$PWD/../../debian/usr/share/applications/miam-player.desktop
        icon64.path = /usr/share/icons/hicolor/64x64/apps
        icon64.files = $$PWD/../../debian/usr/share/icons/hicolor/64x64/apps/application-x-miamplayer.png
        appdata.path = ???
        appdata.files = $$PWD/../../fedora/miam-player.appdata.xml
        INSTALLS += desktop \
	        target \
	        icon64 \
            appdata
    }

**Comment by martinkg** [comment]
the file should be installed in this folder /usr/share/appdata/
/usr/share/appdata/miam-player.xml

**Comment by MBach** [comment]
Hi @martinkg 
File has been added to the repository.

**Comment by martinkg** [comment]
thanks, works.
