### ISSUE TITLE
SIGSEGV with mini-mode plugin

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#86]
I enter minimode, then see that I have no tracks, click next button >>| and:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5d983d8 in operator==(QString const&, QString const&) () from /usr/lib/libQt5Core.so.5

(gdb) backtrace

#0  0x00007ffff5d983d8 in operator==(QString const&, QString const&) () from /usr/lib/libQt5Core.so.5
#1  0x00007ffff6a74b37 in QLabel::setText(QString const&) () from /usr/lib/libQt5Widgets.so.5
#2  0x00007fffd169cad4 in MiniModeWidget::MiniModeWidget(MediaPlayerControl*, QWidget*)::{lambda(QString const&)#3}::operator()(QString const&) const () at minimodewidget.cpp:72
#3  0x00007fffd169f749 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<const QString&>, void, MiniModeWidget::MiniModeWidget(MediaPlayerControl*, QWidget*)::<lambda(const QString&)> >::call(MiniModeWidget::<lambda(const QString&)>, void **) (f=..., arg=0x7fffffffdd90) at /usr/include/qt/QtCore/qobjectdefs_impl.h:495
#4  0x00007fffd169f68c in QtPrivate::Functor<MiniModeWidget::MiniModeWidget(MediaPlayerControl*, QWidget*)::<lambda(const QString&)>, 1>::call<QtPrivate::List<QString const&>, void>(MiniModeWidget::<lambda(const QString&)> &, void *, void **) (
    f=..., arg=0x7fffffffdd90) at /usr/include/qt/QtCore/qobjectdefs_impl.h:552
#5  0x00007fffd169f4c2 in QtPrivate::QFunctorSlotObject<MiniModeWidget::MiniModeWidget(MediaPlayerControl*, QWidget*)::<lambda(const QString&)>, 1, QtPrivate::List<const QString&>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0x1714dd0, r=0xa2a5b0, a=0x7fffffffdd90, ret=0x0) at /usr/include/qt/QtCore/qobject_impl.h:192
#6  0x00007ffff5f161a7 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#7  0x00007ffff774123d in MediaPlayer::currentMediaChanged (this=0xa2a5b0, _t1=...) at debug/.moc/moc_mediaplayer.cpp:228
#8  0x00007ffff77200d5 in MediaPlayer::MediaPlayer(QObject*)::{lambda()#2}::operator()() const () at mediaplayer.cpp:35
#9  0x00007ffff77222e7 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, MediaPlayer::MediaPlayer(QObject*)::<lambda()> >::call(MediaPlayer::<lambda()>, void **) (f=..., arg=0x7fffffffdf50)
    at /usr/include/qt/QtCore/qobjectdefs_impl.h:495
#10 0x00007ffff77221e9 in QtPrivate::Functor<MediaPlayer::MediaPlayer(QObject*)::<lambda()>, 0>::call<QtPrivate::List<>, void>(MediaPlayer::<lambda()> &, void *, void **) (f=..., arg=0x7fffffffdf50) at /usr/include/qt/QtCore/qobjectdefs_impl.h:552
#11 0x00007ffff7721f34 in QtPrivate::QFunctorSlotObject<MediaPlayer::MediaPlayer(QObject*)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0xa32710, r=0xa2a5b0, 
    a=0x7fffffffdf50, ret=0x0) at /usr/include/qt/QtCore/qobject_impl.h:192
#12 0x00007ffff5f161a7 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#13 0x00007ffff46f47f7 in ?? () from /usr/lib/libQtAV.so.1
#14 0x00007ffff5f171e1 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#15 0x00007ffff692e9ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff6933e86 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff5ee7bab in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#18 0x00007ffff5ee9fa6 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/libQt5Core.so.5
#19 0x00007ffff5f3e143 in ?? () from /usr/lib/libQt5Core.so.5
#20 0x00007ffff4066dc7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#21 0x00007ffff4067020 in ?? () from /usr/lib/libglib-2.0.so.0
#22 0x00007ffff40670cc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#23 0x00007ffff5f3e54f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#24 0x00007ffff5ee557a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#25 0x00007ffff5eed53c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#26 0x00000000004c7234 in main (argc=1, argv=0x7fffffffe778) at main.cpp:77

**Comment by MBach** [comment]
Hmm...

I don't think you have to bother with plugins right now. I should close the chapter 0.8.0 for now and release the sources.

I think I have some big adjustments to make plugins to work on all platforms, and I have to make things much simpler for cross compiling.

**Comment by MBach** [comment]
Check this out:
https://github.com/MBach/Miam-Player/commit/0fe1c75b0ee47db1d091d184264ee1ebc49b1017
and
https://github.com/MBach/mini-mode/commit/a515f855ab4d46f61f7a0044b389412f7d797257
