### ISSUE TITLE
Unnecessary GroupBox title in Cover Fetch plugin

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#87]
templateCover.ui provides GroupBox title in cover fetch dialog (see 53 line). 
![screen](https://cloud.githubusercontent.com/assets/1446573/13033474/8810096c-d328-11e5-90f4-a05291840cbc.png)

Also Artist string is not marked to be translated. See Artist:Akira Yamaoka on the screenshot.

**Comment by Ilya87** [comment]
One more remark about playlist behaviour: I can't drag and drop tracks to the bottom of list from tree view without making current last track last after dropping (I can drag only before it).

**Comment by MBach** [comment]
Hi @Ilya87 
Those GroupBoxes stand for Local and Remote covers. However, this is quite redundant when you have selected one or more Artists with at least 2 Albums. You'll see _n_ times these GroupBox and might be the best way to tell the user.
Actually, I'm wondering if I need to rewrite completely the UI and change a little the behavior of this plugin.

**Comment by MBach** [comment]
Hi,
What do you think of this:
![issue_87](https://cloud.githubusercontent.com/assets/1532657/22671166/3289de22-eccd-11e6-98e3-971a94d8621c.png)

**Comment by Ilya87** [comment]
Looks nice to me.

**Comment by MBach** [comment]
OK so I'm closing this issue
