### ISSUE TITLE
Not working del shortcut

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#88]
I can't use del key after Miam-Player's start to delete track. Only after I start playback of any track I can use this key.

**Comment by MBach** [comment]
This commit should fix it: https://github.com/MBach/Miam-Player/commit/2f77e2933af59ecab7d787455da82822992044bd

Some shortcuts are overridden by some other widgets, and they aren't forwarded to parent. So they are not triggered. I still need to locate them precisely.
