### ISSUE TITLE
Missing tracks in Library list

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#98]
1). I installed the latest git version, deleted config folders and got after Library scan no tracks in Library view («Artist->Album->track 1, track 2» type).
2). Also I can't add many files by drag'n'drop to the playlist.
3). I can't change default playback buttons to my Keyboard's mediabuttons - they all restore go to default value when I close settings window.

**Comment by MBach** [comment]
1. Should be fixed with: https://github.com/MBach/Miam-Player/commit/2dc0dbac4f27d2756c060c78744323c02f0ae692
2. What do you mean by many? 100, 1000, 10000 files?
3. This point is related to #69, I have some work to do with default shortcuts

**Comment by Ilya87** [comment]
2 - I mean I simply can't do this, not amount, but in principle. As filemanager I use latest pcmanfm-qt.

**Comment by MBach** [comment]
Well... I confess I have put this work on hold! Here's what I have right now in the code:

    QDropEvent *de = static_cast<QDropEvent*>(event);
    if (de->source() == nullptr) {
        // Drag & Drop comes from another application but has landed in the playlist area
        de->ignore();
        //QDropEvent *d = new QDropEvent(de->pos(), de->possibleActions(), de->mimeData(), de->mouseButtons(), de->keyboardModifiers());
        /// FIXME
        //_mainWindow->dispatchDrop(d);
        return true;
    }

There is a big FIXME in the code :( I have made big changes with lazy loading mode, and the Playlist Area doesn't belong anymore to the MainWindow, and I didn't find a proper solution.

**Comment by MBach** [comment]
I think this commit fixed it: https://github.com/MBach/Miam-Player/commit/de04a5cf18c435b779507572995757d5fa3cca7a

PS: I also have other work about the daemon thread which keeps the library up-to-date when one has activated this option in settings.

Please wait a few days (or weeks...) before opening multiple issues about this!

**Comment by Ilya87** [comment]
Yes, now I can drag and drop, but dropped mp4 audio tracks from file manager are displayed with «error reading artist» message while they are shown normally in Library.

**Comment by MBach** [comment]
Hi @Ilya87 
Can you provide:
- which desktop and window manager do you use: like LXDE for example
- some mp4 files
Because on my VM, I have tested this configuration with some m4a audio file (like mp4) and it's working.
![pcmanfm-qt](https://cloud.githubusercontent.com/assets/1532657/13997158/0e2f0e50-f131-11e5-9b1f-e52e7f9834bd.png)

**Comment by Ilya87** [comment]
I use LXQt. https://yadi.sk/d/lw4uis1AqT4iA - Apocalyptica file. I use openbox as WM. As I already mentioned problem with drag and drop was solved, but reading mp4 tags gives error.

**Comment by MBach** [comment]
Thank you @Ilya87, I've found the problem about drag & drop.
The behavior isn't the same when I'm dropping a folder or when I'm dropping tracks. I thought is was, but something is wrong. I'll fix this soon.

**Comment by MBach** [comment]
I didn't find a multiplatform solution so here's the patch...

    #if defined (Q_OS_WIN)
        urls << QUrl::fromLocalFile(t);
    #else
        urls << QUrl(t);
    #endif

https://github.com/MBach/Miam-Player/commit/12b978b257a794bfb1d79f4163a957223b425ada

**Comment by Ilya87** [comment]
Fixed. Thank you.
